parprog : calculatecutset.cpp celllist.cpp channelRouting.cpp classifyNets.cpp dvalues.cpp gain.cpp globalRouting.cpp layoutOperations.cpp linkedList.cpp main.cpp pass.cpp constraintList.cpp
	g++ -o parprog calculatecutset.cpp celllist.cpp channelRouting.cpp classifyNets.cpp dvalues.cpp gain.cpp globalRouting.cpp layoutOperations.cpp linkedList.cpp main.cpp pass.cpp constraintList.cpp
